wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.15.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721268725.308669
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      3:
      - 23
      4: 3.11.9
      5: 0.15.0
      8:
      - 3
      - 5
